server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:planit}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

#  sql:
#    init:
#      mode: always

jwt:
  secret: ${JWT_SECRET:IAMAKSHRKHIAMAKSHARKHIAMAKSHARKH1234988765IAMakshar}
  expirationMs: 10800000
  refreshExpirationMs: 604800000

google:
  clientId: 954694610792-od254vr5ae61nh9buf0bo309mk4oo7eu.apps.googleusercontent.com

apple:
  teamId: ${APPLE_TEAM_ID:}
  clientId: ${APPLE_CLIENT_ID:}
  keyId: ${APPLE_KEY_ID:}

cors:
  allowed-origins:
    - http://localhost:5173

